### ISSUE TITLE
There is a problem with restoring Night Vision charge

### ISSUE THREAD

**Issue by Paradox75831004** [Malcolm-Q/LC-LateGameUpgrades#100]
In some games, when I recreated, I bought an improvement for NV in advance, and after the points - why the charge was more than usual. If you buy glasses, put them on, and only then pump up their charge to level 4, then it’s even more or less balanced. And so with the first moment - you have the longest night vision charge + when it runs out, it is restored in a few seconds

**Comment by WhiteSpike** [comment]
In the testing I have been doing, all tests shown the drain and regeneration of night vision to act according to what it's displayed in the respective info of "NV Headset Batteries" (which also takes account of the increase of night vision's maximum battery per level)

Can you clarify a bit more what seems to be the issue with night vision, please? Is night vision drain/regen not match up with what says in "info NV Headset Batteries"?

If the problem is that it has too much battery capacity increase, battery drain decrease or battery regen increase, you can change these values in the configuration of this mod.

**Comment by Malcolm-Q** [comment]
Inactive - closing

The user likely has old config values for night vision.
