### ISSUE TITLE
The Peeper Item doesn't work

### ISSUE THREAD

**Issue by DigitalIver** [Malcolm-Q/LC-LateGameUpgrades#105]
The peeper doesn't make coil head stand still in other word doesn't work

**Comment by Malcolm-Q** [comment]
Next update today should fix this

**Comment by WhiteSpike** [comment]
Okay, related to the peeper, it now does stop the coil from moving.
HOWEVER, it only does it if the coil is targetting a player which is not desireable since once everyone leaves the facility, the coil heads moved out of range of peeper and you will just be confused when you come back in.

I have been able to make a fix to this [issue](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/107) so worry not, the peeper, after many refactors on it, maybe will work as it was intended to do at later update.
