### ISSUE TITLE
Bigger lungs does not obey the price in config

### ISSUE THREAD

**Issue by ImpulsiveLad** [Malcolm-Q/LC-LateGameUpgrades#114]
Its worked before but on a similar note, you can have as many levels for perks like bigger lungs and such right?

**Comment by WhiteSpike** [comment]
Fixed this [issue](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/118). It was using Running Shoes' instead of his own.

The amount of levels is dependent on the amount of prices you put in each upgrades' upgrade prices parameter, yes.
If you have "100,200,300,400,500,600,700" in Bigger Lungs' Upgrade Prices, you will have 7 levels with respective prices.

**Comment by ImpulsiveLad** [comment]
Ah that would make sense, just testing about I had 8 or so levels of bask muscles I made 5 each. I think I was just confused if it worked or not since I upgraded bigger lungs last night and now we know that wasn’t touted to the config correctly. Thanks
