### ISSUE TITLE
Shopping Cart Despawn

### ISSUE THREAD

**Issue by BenjKind** [Malcolm-Q/LC-LateGameUpgrades#171]
After finding the shopping cart and using it several times, when placed on the edge of the ship to keep it out of the way. Once reloading the save the shopping cart vanishes and is no longer available.

Steps to replicate:
- Find shopping cart as scrap
- Place in ship slightly withinin the wall
- Reload Save
- Cart vanishes

Mod Version - 1.0.1
Installed via - r2modman
Many mods were installed potentially is related to incompatibilities and may not be replicable.

**Comment by WhiteSpike** [comment]
The problem as of now is that I'm essentially making a new copy of itemProperties of the wheelbarrow/shopping cart so that I can just change the item properties of each wheelbarrow more easily. If I hadn't, it would lead to all wheelbarrow's of the same type of be having the exact same weight.

But after finding out that the game checks each itemProperties through REFERENCE to a list, I will have to be creative with how to handle the wheelbarrow's weight without that reflecting on other wheelbarrows of its same type.

**Comment by WhiteSpike** [comment]
Made a [pull request](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/184) which seemed to fixed the issue of wheelbarrows/shopping carts not saving. Will be live in next release.
