### ISSUE TITLE
Multitude of wheelbarrow buggies

### ISSUE THREAD

**Issue by ImpulsiveLad** [Malcolm-Q/LC-LateGameUpgrades#204]
1. Starting with an unknown, if the wheelbarrow scrap false config refers to the cart then it does not work, otherwise then I would recommend a config is added to disable cart scrap spawning.

2. Both the item cap and individual weight of the wheelbarrow is 1 higher than intended (30lb is 31lbs) (5 scrap is 6 scrap)

3. I have only seem the wheelbarrow be held normally on a host and when spectating someone with it, otherwise its help like a guitar or like a bow.

4. Scrap in the wheelbarrow/cart do not count towards the "x/y scrap collected" on leaving the planet.
Loggy woggie [LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/13959346/LogOutput.log)

**Comment by WhiteSpike** [comment]
From the [pull request](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/206):
1. is possibly fixed.
2. the weight issue is fixed, never managed to replicate the items issue
3. Can't replicate and even if I could, I won't fix because it's an issue with the animators which are related to vanila and/or other mods that mess with the animators. The only time this mod messes with the player's animators is when they get revived through interns command and it's just used to play the normal animation of being revived in the ship. Nowhere else in this mod is the animator being messed with.
4. Fixed.
