### ISSUE TITLE
Picking up NV Goggles gives everyone in lobby NV Goggles

### ISSUE THREAD

**Issue by HappyPotatoFunTime** [Malcolm-Q/LC-LateGameUpgrades#244]
As the name implies. Picking up NV Goggles gives everyone in an MP lobby NV Goggles, rather than each individual giving nv goggles to the person that bought/picked it up.

**Comment by WhiteSpike** [comment]
From what you described, you had in the NV's configuration entry for "Individual Purchase" set to false which lead to NV being enabled on everyone.

If you wish for the NV item to only give NV to who uses it, you need the individual entry as true.

**Comment by HappyPotatoFunTime** [comment]
The issue is that "Individual Purchase" is set as "True". All configurations have been set to ensure this wouldn't happen including "Convert all upgrades to be shared" being set as "False", and everyone having the same config files. Not sure if it's been fixed with the latest update, but it's hard to test as of right now due to this involving multiple people.


Also, appreciation given for the wheelbarrow fix.

**Comment by WhiteSpike** [comment]
I found the [problem](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/254) and should be fixed in next release.

Essentialy, due to readibility, we have a dictionary called "IndividualUpgrades" which stores if an upgrade is **shared** or not so when I went to read the code in night vision, it made sense to me when I read the line. But when I went back to see what the dictionary is actually storing, I realized that it was doing "If not shared, share to all" instead of "if shared, share to all". ;)
