### ISSUE TITLE
Baboon Hawks excessively camp Shopping Carts

### ISSUE THREAD

**Issue by MusicalRess** [Malcolm-Q/LC-LateGameUpgrades#248]
This has happened both on vanilla 'Offence', and on modded 'Aquatis' (has a lot of baboon hawks) but may happen anywhere.

Hawks seem to notice the items inside of shopping carts / wheelbarrows and cannot seem to pick them up. Instead they keep trying to by sitting on top of the cart and guarding it with their life. While holding a cart full of items the hawks will become _A Lot_ more aggressive towards you even if you outnumber them as they try to camp the cart-held items in front of you.

This creates a few issues; the first obvious one being that you cant easily retrieve the cart from the hawks, and the second: Stormy weather. You can easily farm Hawk samples with a shopping cart easily and consistently since they glue themselves to the conductive items. Feels like cheating sometimes.

To Reproduce:
 - Have a shopping cart or wheelbarrow with an item inside
 - Locate a Baboon Hawk (Aquatis has a lot even during the start of the day)
 - Place or hold the cart near them and observe their behaviour. (Placing it near them will probably yield more consistent results.)

Update:
I have retested this with LategameUpgrades, Aquatis, and the Minimap Mod
Upon placing an empty cart near them they showed no interest, but upon placing a flask inside they immediately started to attack me and hurry me away from the cart before returning to it and just sitting there.
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/158001555/dc91a2e3-3e73-4644-a7d9-d769fb3efac5) 
I then placed a wheelbarrow (1 item) near them and they focused entirely on that instead.
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/158001555/c61d67a2-4c67-46af-b671-17e1639a6b75)
They also do a 'Ritual Dance' around the cart which is really funny.
[LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14087205/LogOutput.log)

**Comment by WhiteSpike** [comment]
They seem to be trying to grab the item on top of the wheelbarrow but since it doesn't meet the requirements to being grabbed (apparently it needs to be at a certain angle from their eyes to the item?), they stop then try again moments later, stuck on this cycle.

Tried to see if setting grabbableToEnemies to false would fix this issue when it's on the wheelbarrow til I saw that baboon completely ignores this item's attribute.

**Comment by WhiteSpike** [comment]
Made a [pull request](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/250) which seem to solve this issue. It will be live in next release.

Since its AI has some missing components regarding items (for example ignoring an item's 'grabbableToEnemies' field), I won't dwell too much into its AI as it can cause issues at later updates. This way, even if there's an update, won't affect much of its AI if it crashes.
