### ISSUE TITLE
About the issues that occur in old save files after updating the mod.

### ISSUE THREAD

**Issue by samasmaqwq** [Malcolm-Q/LC-LateGameUpgrades#314]
The "lategame" items in the old save file are messed up and downgraded; some features are not working as expected, such as the boombox buff ,  it doesn't have any actual effect.

**Comment by WhiteSpike** [comment]
When you say "items", you mean the items we provide or upgrades?

I tried my [best](https://github.com/Malcolm-Q/LC-LateGameUpgrades/blob/07b831d4b30747cfd753d424de38931f634058a5/MoreShipUpgrades/Managers/LGUStore.cs#L184) at carrying over the save data from old saves into the new save format so that nothing is lost when moving into 3.2.0 version.

So are you saying that the upgrades don't get loaded or that they are being loaded but do nothing?

**Comment by samasmaqwq** [comment]
Sorry, I mainly play 'Lategame Store' and some upgrades do not work only in old saves. Now, I have not encountered the above issues in my new save created in the latest version.
