### ISSUE TITLE
Questions about the "intern" command.

### ISSUE THREAD

**Issue by FireGeneral** [Malcolm-Q/LC-LateGameUpgrades#34]
Replaces your dead friend with a fresh intern (revives your friend).

Can you explain further what exactly will happen if I use this command on my dead friends?

Will they have their character ranks reset since they're replaced with fresh interns?
How about their outfits? Will the revived characters still have their outfits or they'll be wearing the default orange?
Their original body?
Will the revived characters have anything usable on them once they're revived? If not, since revived players will be teleported to a random location in the facility, they'll be in a situation just like inverse teleporter?

**Comment by Malcolm-Q** [comment]
Ranks shouldn't be reset outfits should be the same, it's nearly the same code that's called when you are revived normally except instead of teleporting you inside the ship it teleports you to a random location in the facility. All items are lost when you die so they won't have the items they previously held. They should have their upgrades still however.
