### ISSUE TITLE
Upgrades not saving between sessions, even for host

### ISSUE THREAD

**Issue by McGodMan** [Malcolm-Q/LC-LateGameUpgrades#408]
Steps to reproduce:
1. Install LateGameUpgrades and dependencies
2. Install InfiniteMoney (or other mod which adds excessive funds for testing) plus dependencies
3. Create a new save
4. Buy a noticeable upgrade (e.g. Running Shoes, Strong Legs, Bigger Lungs, etc...)
5. Leave save
6. Rejoin save
7. Upgrade unpurchased

Happens even when going down to a planet and back up which usually fixes this sort of issue.
Happens even when just using the money mod to get money then restarting with just LGU.

Another issue I've noticed is that if you rejoin a save without restarting the game the upgrades will no longer apply even when bought again and will for some reason skip even levels when purchased (e.g. 1 3 5 instead of 1 2 3 4), these upgrades are also not saved as purchased.

log:
[LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14736801/LogOutput.log)

**Comment by SnackSBR** [comment]
the upgrades only save with lethal company auto save (coming back from the planet)

About the reconnecting without restarting the game could you try this https://github.com/Malcolm-Q/LC-LateGameUpgrades/issues/406#issuecomment-2018747490 ?

**Comment by ShoukakuChuuCC** [comment]
Same problem, everything works fine with v3.3.1

**Comment by McGodMan** [comment]
Going down to any planet (minus the company when you don't have quota) works as you said, my apologies I didn't realize that's how it worked.

The dll worked for fixing the numbers and applying the upgrades when bought, however, upgrades bought before the current session don't apply until the game is restarted.

I haven't had the chance to test it with friends yet so I'll get back to you on that when I can.

**Comment by WhiteSpike** [comment]
> however, upgrades bought before the current session don't apply until the game is restarted.

And no errors appear in the console for either host and/or client?

**Comment by McGodMan** [comment]
I've just checked and a single error appears when opening the terminal. Other than that there were a few warnings (a lot concerning audio) but none seemed to be about LGU. I am the host and my friends aren't off work yet but they should be in a few hours.

[Host Log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14762112/LogOutput.log)

Steps taken:
1. Start new save
2. Max out running shoes as it's most noticeable
3. Go down to a planet then immediately back up
4. Quit to menu
5. Re-enter save
6. See running shoes is still maxed out but have no speed increase

Here's the code for the mods I'm using (it's just LGU, it's dependencies and a mod which gives me infinite money). I am using the dll you recommended instead of the vanilla v.3.4.3 one.

Code: 018e7bbf-a393-fb98-9333-038b70de7cb0

**Comment by McGodMan** [comment]
Just got on with a friend to test it and while the upgrades do save when returning from a moon they only save for me and not my friend (this is for the first session after a restart, the original issue). From what I can tell from the log it doesn't seem to load any data for my friend when they join but does load the data for me. We haven't modified the config and are both using the dll you linked.

Here are the logs:
[Host Log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14763589/LogOutput.log)
[Player 2 Log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14763592/LogOutput.log)

By the way, I might've accidentally linked the wrong log on my previous comment, please disregard it. I have recreated the log by doing the exact same thing I did before.

[Host Log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14763611/LogOutput.log) for previous comment.

It should be noted that my friend bought the upgrades but they only saved for me, I also had him leave before I closed the save to be sure but he still ended up not having the upgrade save (it showed level 0 in the store for him). We also both restarted before rejoining the save to avoid the issues listed in my previous comment.

Thanks in advance

**Comment by SnackSBR** [comment]
[MoreShipUpgrades.zip](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14764896/MoreShipUpgrades.zip)
could you give this version a go?

**Comment by McGodMan** [comment]
Tried using that version, the game seems to no longer connect to steam's servers, neither me nor my friend can connect even after restarting steam (even in LAN). It also seems to break steams ability to connect to the internet which requires a restart after opening the game.

The issue with re-logging doesn't seem to be fixed and gives the same result as before.

Log 1 is me trying to connect via steam.
Log 2 is me seeing if the issue presented in [this comment](https://github.com/Malcolm-Q/LC-LateGameUpgrades/issues/408#issuecomment-2021024124) was fixed.

Here's the logs:
[Host Log 1](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14765238/LogOutput.log)
[Host Log 2](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14765301/LogOutput.log)

My friend has gone off for the night so any future fixes for the main issue can't be tested til tomorrow evening. I can still test for the second issue with re-logging though.

**Comment by SnackSBR** [comment]
Today is steam maintenance day. It gets quite unstable.

**Comment by McGodMan** [comment]
I'll test it again in the morning, I shouldn't need another player to see if it connects to steam. Hopefully it is just a steam maintenance issue.

I should be able to test the multiplayer part tomorrow evening, about 19-20 hours from now.

Thanks again

**Comment by McGodMan** [comment]
Tested it again, upgrades bought load when rejoining after a restart for both host and client. Previous upgrades do not load (though they still appear as bought) when re-logging without restarting. The main issue seems to be fixed.

The logs contain both the rejoin after a restart and the re-logging without restart as they were done in the same session.

[Host Log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14779378/LogOutput.log)
[Player 2 Log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14779393/log.txt)

Thanks again

**Comment by WhiteSpike** [comment]
Player 2's log is essentialy empty.

Logs don't show them applying and there are no errors popping up so the upgrades aren't being saved (which in case you don't know that the saving point is when you exit out of a moon, same as vanilla when the autosaving UI appears on the bottom right corner).

**Comment by McGodMan** [comment]
My bad, I didn't check the log before submitting, my friend sent the wrong one over.

Here's the actual log:
[Player 2 log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14780122/LogOutput.log)

Sorry about that

**Comment by Schurches** [comment]
Hi! I think I'm facing the same issue as the one reported in this thread, so I'll add my logs as well :)

My list of mods is quite big so I've added listed them all in this file:
[modsListAndVersions.txt](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14783663/modsListAndVersions.txt)
The ones with "-OFF" next to the version are disabled. All others are enabled.

This are the logs that were generated during my playthrough:
[lateGameUpgradesLog.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14783583/lateGameUpgradesLog.log)

Steps to reproduce:
- Start the game
- Load a savefile with upgrades already purchased (In my scenario, I loaded one where I had almost everything maxed out. Muscles, Lungs, Quantum Disruptor, Shoes, Legs...) 
- Confirm that the upgrades were successfully activated (Via terminal and chat outputs)
- Land in any moon (Optional)
- Exit the game by going back to the main menu
- Load a savefile with upgrades already purchased (In this scenario I loaded the same one)

The first time you load a file everything works fine. However, if you try to re-load it or load a different one within the same game session you'll face a null pointer exception the second time the LGU tries to init. 

The following line corresponds to the first time that the mod loads
Line #865: [Info   :More Ship Upgrades] [LguStore] Loading SteamID: 76561198325956475

These ones correspond to the second time it loads:
Line #1870: [Info   :More Ship Upgrades] [LguStore] Loading SteamID: 76561198325956475
Line #1880: [Info   :More Ship Upgrades] [LguStore] Applying loaded upgrades...
[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.GameObject.GetComponent[T] () (at <e27997765c1848b09d8073e5d642717a>:IL_0021)
MoreShipUpgrades.Managers.LguStore+<WaitForUpgradeObject>d__32.MoveNext () (at <735e013087c346648ba6eb478a3f76e9>:IL_00FE)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

The only way I've been able to workaround this issue is by closing the game completely, starting it again and loading the save file.
I'm using the latest version of the LGU: v3.4.3; This issue was not present on the previous.

I hope my input helps :)
