### ISSUE TITLE
new terminal api breaks

### ISSUE THREAD

**Issue by TheDiamondMage** [Malcolm-Q/LC-LateGameUpgrades#419]
When loading the terminal api via the 'lgu' command, the new interface comes up, but I can't interact with it. The console log gives the following:
![Screenshot 2024-04-02 224510](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/106934023/f34f706b-92b9-4fe6-9b7f-e0d810bc8fec)

**Comment by CheriTM** [comment]
I am also having this issue.

**Comment by WhiteSpike** [comment]
This was an issue in v49 because latest release at the time was for v50 *only*. 3.5.2 *should* allow you to use the menu as it works in both v49 and v50.

However, if it still persists, please post the *whole* log output file when something supposed to happen does not happen. An error appearing that moment could be a consequence of a previous fault and it's really difficult to know the cause with just some information.

**Comment by WhiteSpike** [comment]
Closing due to lack of response so assuming it's no longer an issue in current release.
