### ISSUE TITLE
LC v50 - Enemies not spawning, LogOutput error spam

### ISSUE THREAD

**Issue by King-Wedgie** [Malcolm-Q/LC-LateGameUpgrades#420]
[LogOutput2024-04-03-0129.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14847323/LogOutput2024-04-03-0129.log)

Launched with r2modman (not Thunderstore). No other mods except dependencies: 
LethalLib v0.15.0; 
HookGenPatcher v0.0.5; 
CSync v4.1.0
FixPluginTypesSerialization v1.1.1 (dependency for CSync)
LethalCompany_InputUtils v 0.7.3
Lategame_Upgrades v3.5.1 (log says More Ship Upgrades v3.5.0, but r2modman says v3.5.1)

After launch, start a new save or continue an existing one. Route to any moon and land. Watch as the BepInEx console (and log) begins to fill with error spam:
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoundManager.Update () (at <126a87ecbe81427089f4bae3b253432b>:IL_004D)
```

Items/scrap, turrets, and mines all spawn as normal. Enemies never spawn.

**Comment by Fluffal32** [comment]
long ago it all runs smoothly with v49, then everything changed when v50 launched. Only landmines & turrets appeared to spawn with monster nowhere to be found :(

**Comment by suwonsarara** [comment]
This is caused by the LethalLib mod. Disabling this mod allows spawn to proceed. Unfortunately, Lategame Upgrades depends on this mod. Additionally, I previously attempted to use Malware Broadcaster in v50, but it didn't work. Specifically, after entering the corresponding landmines and turrets, the output has been disabled, preventing the number from being output. I'm not sure if this has been fixed.

**Comment by King-Wedgie** [comment]
@suwonsarara is correct. After some more testing, I can confirm this is an issue specifically with LethalLib and not LGU. The issue has already been posted in LethalLib's [issue tracker](https://github.com/EvaisaDev/LethalLib/issues/72).

Closing this as "not planned" since this isn't specific to LGU.
