### ISSUE TITLE
Can't update pack to 3.5.X because of the new FixPluginTypesSerialization dependency.

### ISSUE THREAD

**Issue by tapehissorchid** [Malcolm-Q/LC-LateGameUpgrades#431]
As you may know, some custom moons use LethalExpansionCore to work, and some use LethalLevelLoader. Lethal Expansion has been somewhat abandoned, and many moons have switched over to LethalLevelLoader, but some great ones haven't. I haven't had any issue getting both types of moons to work on the same build by just using LethalExpansionCore and not LethalExpansion and also having LethalLevelLoader installed. 

For some reason, FixPluginTypesSerialization causes my build to only load/show moons that work on LethalExpansionCore. Anything using LethalLevelLoader is hidden. If I remove FixPluginTypesSerialization, it fixes this issue, but LateGameUpgrades doesn't run. 

I'm not versed on how these things work so please let me know what info you need and I'll be happy to provide.

**Comment by WhiteSpike** [comment]
Are you using **both** LethalLevelLoader and LethalLevelLoaderFixed?
If yes, the problem is that Unity is using LethalLevelLoader's serializers for LethalLevelLoaderFixed things when it's supposed not to (because the plugin tells Unity what is Serializable and what is not).
Otherwise, you will have to talk with [CSync's](https://github.com/lc-sigurd/CSync) developer to clarify what the issue is exactly but this is what I gathered when looking into this issue.

**Comment by tapehissorchid** [comment]
Oh, yes. That's probably it. I totally forgot about LLL Fixed. I had to add that one a while back because me and my friends were not having weathers synced up as well as the moons loading different custom interiors for us causing non-host players to just fall into nothing. Messing with it now.

**Comment by tapehissorchid** [comment]
Update: That was it. I thought LLL Fixed was just a patch-over for LLL and didn't realize it could run on its own. Disabling LLL fixed the issue. Thanks!
