### ISSUE TITLE
Can't get mod to work

### ISSUE THREAD

**Issue by Forbidden22** [Malcolm-Q/LC-LateGameUpgrades#445]
![image (1)](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/167640268/a93c7d52-1714-4dde-be9c-b01496f06a6e)

the following error occurs when anyone of my friends tries to join whilst lethallib is in their files, however, without lethallib the lategameupgrades doesn't work at all.

Lastly, I will note that all other mods and multiplayer works just fine without lethallib although the lategame upgrades won't be in game at all.

**Comment by WhiteSpike** [comment]
So is the problem with LethalLib or LategameUpgrades?
If it's with LethalLib, you will need to report this to them with proper logs (as in posting the log file that is generated from the console).
If it's with LategameUpgrades spefically, I can't do anything with what you gave me because again, like you said, this mod can't load if you do not have LethalLib installed.

Note that you should mention what version of the game you're playing when reporting an issue as it helps in finding the causes of the problem.

**Comment by TCabecinhas** [comment]
I've run into the same issue, can't be sure if it is from the lethalLib or the mod itself, but the error is the same. We've tested with different versions of lethalLib and nothing was working. Also I am playing in v50

**Comment by Det-Casto** [comment]
Same issue, using Lategame and LethalLib 0.15.1, and the latest thunderstore updates for the other dependencies. I also removed all other mods keeping only Lategame and its dependencies to see if there was mod incompatibility but it still didn't work. I used my main account and my second account with exactly the same files and configs. Using V50 Lethal Company.

**Comment by WhiteSpike** [comment]
Can each provide logs to understand if somethings wrong with the mod?
 I understand you're having an issue but I can't help you right now as I can boot up the game just fine with just the mod and necessary dependencies.

**Comment by Det-Casto** [comment]
I'll post the logs later when I can (around 7 hours). Also the game boots up perfectly fine solo. Other players that join will get the black screen and fog effect with or without the exact same config files, even with no other mods installed and dependencies up to date.
