### ISSUE TITLE
Reseting ALL SETTINGS upon update

### ISSUE THREAD

**Issue by EmeryDoesStuff** [Malcolm-Q/LC-LateGameUpgrades#59]
This update reset EVERY config in the config file. 
can you not

**Comment by Malcolm-Q** [comment]
No.

The config isn't replaced always but in circumstances where it or the behaviours tied to it were changed significantly and the old values would create undesired behaviours the config gets reset.

Nobody reads anything so if I didn't have the config reset this update then instead of a couple people complaining about having to spend 30 seconds resetting a couple values I'd have 20 people a day saying night vision is broken because they're using the old config values.

It's not ideal and I like avoiding it but it's often the least painful route.
